version: '3'
volumes:
  mysql_data:
  vendor_bundle:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - shared_network
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    networks:
      - shared_network
    volumes:
      - ./:/usr/src/app
      - ./vendor/bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    command: bundle exec rails server --binding 0.0.0.0 --port 8080
networks:
  shared_network:
    external: true
